installCRD: true

controller:
  replicas: 1

repoServer:
  replicas: 1

server:
  replicas: 1
  service:
    type: NodePort
    namedTargetPort: false
  # ingress:
  #   enabled: true
  #   annotations:
  #     kubernetes.io/ingress.class: alb
  #     alb.ingress.kubernetes.io/scheme: internet-facing
  #     alb.ingress.kubernetes.io/tags: Environment=dev,Name=argocd-alb

  extraArgs:
    - --insecure
  config:
    accounts.alice: apiKey, login
    url: http://127.0.0.1:30080

    repositories: |
      - url: https://github.com/iamchoiz/k8-cicd-argocd.git
      - url: https://github.com/iamchoiz/k8-monitoring.git
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: cc77c6218f2755bdb6ac
            clientSecret: $another-secret:clientSecret
            orgs:
            - name: devops-argocd

  rbacConfig:
    policy.default: role:readonly
    policy.csv: |
      p, role:local-user-admin, applications, *, */*, allow
      g, alice, role:local-user-admin

      p, role:org-devops, applications, *, */*, allow
      p, role:org-devops, clusters, *, *, allow
      p, role:org-devops, repositories, *, *, allow
      g, devops-argocd:devops, role:org-devops


redis:
  enabled: true

redis-ha:
  enabled: false